---
version: '3'
services:

# START SERVICE schema_registry.sasl
  schema_registry:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.schema_registry.sasl:5.4.0
    environment: ['SCHEMA_REGISTRY_HOST_NAME=schema_registry', 'SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085', 'SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFIED_ALGORITHM=https', 'SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_SSL', 'SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=${SCHEMA_REGISTRY_SASL_ENVIRONMENT_CLOUD_BOOTSTRAP_SERVERS}','SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${SCHEMA_REGISTRY_SASL_ENVIRONMENT_SASL_JAAS_CONFIG_CLUSTER_API_KEY}" password="${SCHEMA_REGISTRY_SASL_ENVIRONMENT_SASL_JAAS_CONFIG_CLUSTER_API_SECRET}";','SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN']
    command: []
    volumes: ['package_schema_registry_sasl_schema_registry_secrets_volume:/etc/schema-registry/secrets']
    ports: [${SCHEMA_REGISTRY_SASL_PORTS}]
    networks: [package_overlay]
    deploy:
      mode: replicated
      replicas: ${SCHEMA_REGISTRY_SASL_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${SCHEMA_REGISTRY_SASL_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${SCHEMA_REGISTRY_SASL_DEPLOY_LABELS}]
    labels: [${SCHEMA_REGISTRY_SASL_LABELS}]
# END SERVICE schema_registry.sasl

volumes: {package_schema_registry_sasl_schema_registry_secrets_volume: { external: true }}
networks: {package_overlay: { external: true }}
