---
version: '3'
services:

# START SERVICE schema_registry.sasl
  schema_registry:
    image: ${CONTECO_REGISTRY}confluentinc/cp-schema-registry:6.0.0 
    environment: ['SCHEMA_REGISTRY_HOST_NAME=schema_registry', 'SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085', 'SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFIED_ALGORITHM=https', 'SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_SSL', 'SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=${SCHEMA_REGISTRY_SASL_ENVIRONMENT_CLOUD_BOOTSTRAP_SERVERS}','SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${SCHEMA_REGISTRY_SASL_ENVIRONMENT_SASL_JAAS_CONFIG_CLUSTER_API_KEY}" password="${SCHEMA_REGISTRY_SASL_ENVIRONMENT_SASL_JAAS_CONFIG_CLUSTER_API_SECRET}";','SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_schema_registry_secrets_volume:/etc/schema-registry/secrets']
    ports: [${SCHEMA_REGISTRY_SASL_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${SCHEMA_REGISTRY_SASL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${SCHEMA_REGISTRY_SASL_COMPOSE_EXTENSIONS}
# END SERVICE schema_registry.sasl

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_schema_registry_secrets_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
