#!/usr/bin/env bash

export CONTECO_LABEL="package.schema_registry_sasl - ModEco"
export CONTECO_DESCRIPTION="Modeco Confluent Schema Registry package, with SASL authentication."

export CONTECO_TYPE="package"
export CONTECO_NAME="schema_registry_sasl"
export CONTECO_TAG="5.4.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
